name: Run Python Script

on:
  workflow_dispatch:  # دکمه "Run workflow" رو فعال می‌کنه

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run main.py
        run: |
          python main.py
